#ifndef KICK_LOG_HH
#define KICK_LOG_HH

#include "soil/Log.hh"

#define KICK_LOG_INIT(x) SOIL_LOG_INIT(x)

#define KICK_TRACE SOIL_TRACE
#define KICK_DEBUG SOIL_DEBUG
#define KICK_INFO  SOIL_INFO
#define KICK_WARNING SOIL_WARNING
#define KICK_ERROR SOIL_ERROR
#define KICK_FATAL SOIL_FATAL
#define KICK_PDU SOIL_PDU


#endif
